[package]
name = "solana"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "solana"
crate-type = ["cdylib"]

[dependencies]
mpl-bubblegum = "1.4.0"
rustler = "0.36.1"
solana-client = "1.14"
solana-program = "1.14"
solana-sdk = "1.14"
